start_pose: [0.0, -1.5, 0.0, -1.57, 0.0, 0.0]
gate_poses:
  - [0.0, -2.0, -0.2, -1.57, 0.0, 0.0]
  - [-1.5, -3.5, 0.0, -3.14, 0.0, 0.0]
  - [-3.0, -5.0, 0.2, -4.71, -1.0, 0.0]
  - [-1.5, -6.5, 0.4, 0.0, 0.0, 0.0]
  - [0.0, -5.0, 0.2, 1.57, 1.0, 0.0]
end_pose: [0.0, -4.5, 0.2, 1.57, 0.0, 0.0]
num_waypoints: 50
gate_radius: 0.5
base_radius: 0.1
expand_radius: 0.1
save_samples: true
N_samples: 10
case_name: "uturn"