case_name: "circle"
nn_type: "gatenet"
bound_method: "backward"
render_method: "splatfacto"
img_folder: "samples"
odd_type: "cylinder"

width: 64
height: 64

debug: True
threshold: [135.0, 145.0, 90.0]