bound_method: "forward"
render_method: "splatfacto"
object_name: "right"
odd_type: "cylinder"
save_filename: "samples"

# width: 256
# height: 256
# fx: 216
# fy: 216
# eps2d: 8.0
# width: 128
# height: 128
# fx: 108
# fy: 108
# eps2d: 4.0
width: 64
height: 64
fx: 54
fy: 54
eps2d: 2.0
tile_size_abstract: 16
tile_size_render: 24
min_distance: 0.01
max_distance: 100.0
gs_batch: 100
part: [1,2,4]

data_time: "2025-05-09_151825"
checkpoint_filename: "step-000040004.ckpt"

bg_img_path: null
bg_pure_color: [1.0, 1.0, 1.0]

save_ref: true
save_bound: true
N_samples: 5


