case_name: "right"
nn_type: "gatenet"
bound_method: "backward"
render_method: "splatfacto"
img_folder: "samples"
odd_type: "cylinder"

width: 64
height: 64

debug: True
threshold: [210.0, 210.0, 130.0]
show_details: False