case_name: "line"
nn_type: "gatenet"
bound_method: "backward"
render_method: "splatfacto"
img_folder: "samples"
odd_type: "cylinder"

width: 64
height: 64

debug: True
threshold: [680.0, 410.0, 470.0]